Feature: Order placement
  As as a customer
  I want to be able to add items to a cart and checkout
  So I can order items from GPBO

  Background:
    Given a logged in customer

  Scenario: Add item to the cart
    When I go to the items page
    And I click on the link "Chocolate Zucchini Muffins"
    Then I should see "View Cart"
    And I should see "Current Price: $9.25"
    When I click on the link "Add to Cart"
    Then I should see "Chocolate Zucchini Muffins was added to cart."
    And I should see "View Cart(1)"
    When I click on the link "View Cart(1)"
    Then I should see "Your Cart"
    And I should see "Chocolate Zucchini Muffins"
    And I should see "Unit Price: $9.25"
    And I should see "Quantity: 1"
    And I should see "Subtotal: $9.25"
  # When I click on the link "Empty Cart"
  # Then I should see "Cart is emptied."
  # And I should see "Your cart is currently empty."
  # And I should see "Start shopping"

  Scenario: Add multiple items to the cart
    When I go to the items page
    And I click on the link "Chocolate Zucchini Muffins"
    Then I should see "View Cart"
    And I should see "Current Price: $9.25"
    When I click on the link "Add to Cart"
    Then I should see "Chocolate Zucchini Muffins was added to cart."
    And I should see "View Cart(1)"
    When I click on the link "View Cart(1)"
    Then I should see "Your Cart"
    And I should see "Chocolate Zucchini Muffins"
    When I click on the link "Continue shopping"
    And I click on the link "Crossiants"
    And I click on the link "Add to Cart"
    Then I should see "Crossiants was added to cart."
    And I should see "View Cart(2)"
    # add a second order of croissants to cart to increase quantity
    When I click on the link "Add to Cart"
    When I click on the link "View Cart(2)"
    Then I should see "Your Cart"
    Then I should see "Crossiants"
    And I should see "Unit Price: $9.50"
    And I should see "Quantity: 2"
    And I should see "Subtotal: $19.00"
    And I should see "Order Summary"
    And I should see "Item Subtotal:"
    And I should see "$28.25"
    And I should see "Shipping:"
    And I should see "$2.00"
    And I should see "Grand Total:"
    And I should see "$30.25"

  Scenario: remove item from the cart
    When I go to the items page
    And I click on the link "Chocolate Zucchini Muffins"
    Then I should see "View Cart"
    And I should see "Current Price: $9.25"
    When I click on the link "Add to Cart"
    Then I should see "Chocolate Zucchini Muffins was added to cart."
    And I should see "View Cart(1)"
    When I click on the link "View Cart(1)"
    Then I should see "Your Cart"
    And I should see "Chocolate Zucchini Muffins"
    When I click on the link "Remove"
    Then I should see "Chocolate Zucchini Muffins was removed from cart."
    And I should see "Your cart is currently empty."
    And I should see "Start shopping"


  Scenario: Empty the cart
    When I go to the items page
    And I click on the link "Chocolate Zucchini Muffins"
    Then I should see "View Cart"
    And I should see "Current Price: $9.25"
    When I click on the link "Add to Cart"
    Then I should see "Chocolate Zucchini Muffins was added to cart."
    And I should see "View Cart(1)"
    When I click on the link "View Cart(1)"
    Then I should see "Your Cart"
    And I should see "Chocolate Zucchini Muffins"
    When I click on the link "Continue shopping"
    And I click on the link "Crossiants"
    And I click on the link "Add to Cart"
    Then I should see "Crossiants was added to cart."
    And I should see "View Cart(2)"
    # add a second order of croissants to cart to increase quantity
    When I click on the link "Add to Cart"
    When I click on the link "View Cart(2)"
    Then I should see "Your Cart"
    Then I should see "Crossiants"
    And I should see "Unit Price: $9.50"
    And I should see "Quantity: 2"
    And I should see "Subtotal: $19.00"
    And I should see "Order Summary"
    And I should see "Item Subtotal:"
    And I should see "$28.25"
    And I should see "Shipping:"
    And I should see "$2.00"
    And I should see "Grand Total:"
    And I should see "$30.25"
    When I click on the link "Empty cart"
    Then I should see "Cart is emptied."
    And I should see "Your cart is currently empty."
    And I should see "Start shopping"
    And I should see "Grand Total:"
    And I should see "$0.00"

  Scenario: Checkout
    When I go to the items page
    And I click on the link "Chocolate Zucchini Muffins"
    Then I should see "View Cart"
    And I should see "Current Price: $9.25"
    When I click on the link "Add to Cart"
    Then I should see "Chocolate Zucchini Muffins was added to cart."
    And I should see "View Cart(1)"
    When I click on the link "View Cart(1)"
    Then I should see "Your Cart"
    And I should see "Chocolate Zucchini Muffins"
    When I click on the link "Continue shopping"
    And I click on the link "Crossiants"
    And I click on the link "Add to Cart"
    Then I should see "Crossiants was added to cart."
    And I should see "View Cart(2)"
    # add a second order of croissants to cart to increase quantity
    When I click on the link "Add to Cart"
    When I click on the link "View Cart(2)"
    Then I should see "Your Cart"
    Then I should see "Crossiants"
    And I should see "Unit Price: $9.50"
    And I should see "Quantity: 2"
    And I should see "Subtotal: $19.00"
    And I should see "Order Summary"
    And I should see "Item Subtotal:"
    And I should see "$28.25"
    And I should see "Shipping:"
    And I should see "$2.00"
    And I should see "Grand Total:"
    And I should see "$30.25"
    When I click on the link "Checkout"
    # Then show me the page
    And I select "Alex Egan - 5000 Forbes Avenue Pittsburgh, PA 15213" from "order_address_id"
    And I fill in "order_credit_card_number" with "4444111122225555"
    And I select "9" from "order_expiration_month"
    And I select "2027" from "order_expiration_year"
    And I press "Place order"
    Then I should see "Thank you for ordering from Roi du Pain."
    And I should see "Order Details"
    And I should see "Total Weight: 3.1 lbs"
    And I should see "Total Cost: $30.25"
    And I should see "Recipient: Alex Egan"